# Form implementation generated from reading ui file 'resultwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import json
from pathlib import Path

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResultWindow(object):
    def setupUi(self, ResultWindow):
        ResultWindow.setObjectName("ResultWindow")
        ResultWindow.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ResultWindow.sizePolicy().hasHeightForWidth())
        ResultWindow.setSizePolicy(sizePolicy)
        ResultWindow.setMinimumSize(QtCore.QSize(720, 360))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ResultWindow)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=ResultWindow)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.wideLayout = QtWidgets.QHBoxLayout()
        self.wideLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.wideLayout.setObjectName("wideLayout")
        self.widenessScrollArea = QtWidgets.QScrollArea(parent=self.tab)
        self.widenessScrollArea.setWidgetResizable(True)
        self.widenessScrollArea.setObjectName("widenessScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 330))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.verticalLayout_10)
        self.skewednessLayout = QtWidgets.QVBoxLayout()
        self.skewednessLayout.setObjectName("skewednessLayout")
        self.skewednessTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.skewednessTitle.setObjectName("skewednessTitle")
        self.skewednessLayout.addWidget(self.skewednessTitle)
        self.skewednessUpward = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.skewednessUpward.setObjectName("skewednessUpward")
        self.skewednessLayout.addWidget(self.skewednessUpward)
        self.skewednessRightward = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.skewednessRightward.setObjectName("skewednessRightward")
        self.skewednessLayout.addWidget(self.skewednessRightward)
        self.verticalLayout_4.addLayout(self.skewednessLayout)
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.verticalLayout_4.addWidget(self.frame)
        self.widenessLayout = QtWidgets.QVBoxLayout()
        self.widenessLayout.setObjectName("widenessLayout")
        self.widenessTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.widenessTitle.setObjectName("widenessTitle")
        self.widenessLayout.addWidget(self.widenessTitle)
        self.widenessHorizontal = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.widenessHorizontal.setObjectName("widenessHorizontal")
        self.widenessLayout.addWidget(self.widenessHorizontal)
        self.widenessVertical = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.widenessVertical.setObjectName("widenessVertical")
        self.widenessLayout.addWidget(self.widenessVertical)
        self.verticalLayout_4.addLayout(self.widenessLayout)
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4.addWidget(self.frame_2)
        self.widenessRawResultsLayout = QtWidgets.QVBoxLayout()
        self.widenessRawResultsLayout.setObjectName("widenessRawResultsLayout")
        self.widenessRawResultsTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.widenessRawResultsTitle.setObjectName("widenessRawResultsTitle")
        self.widenessRawResultsLayout.addWidget(self.widenessRawResultsTitle)
        self.widenessRawResults = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.widenessRawResults.setObjectName("widenessRawResults")
        self.widenessRawResultsLayout.addWidget(self.widenessRawResults)
        self.verticalLayout_4.addLayout(self.widenessRawResultsLayout)
        self.widenessScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.wideLayout.addWidget(self.widenessScrollArea)
        self.wideGraphLayout = QtWidgets.QVBoxLayout()
        self.wideGraphLayout.setObjectName("wideGraphLayout")
        self.wideLayout.addLayout(self.wideGraphLayout)
        self.verticalLayout_6.addLayout(self.wideLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rotateLayout = QtWidgets.QHBoxLayout()
        self.rotateLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.rotateLayout.setObjectName("rotateLayout")
        self.rotatednessScrollArea = QtWidgets.QScrollArea(parent=self.tab_2)
        self.rotatednessScrollArea.setWidgetResizable(True)
        self.rotatednessScrollArea.setObjectName("rotatednessScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 748, 330))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rotatednessTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.rotatednessTitle.setObjectName("rotatednessTitle")
        self.verticalLayout.addWidget(self.rotatednessTitle)
        self.rotatednessResult = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.rotatednessResult.setObjectName("rotatednessResult")
        self.verticalLayout.addWidget(self.rotatednessResult)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.frame_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(4)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rotatednessRawResultsTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.rotatednessRawResultsTitle.setObjectName("rotatednessRawResultsTitle")
        self.verticalLayout_5.addWidget(self.rotatednessRawResultsTitle)
        self.rotatednessRawResults = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents_2)
        self.rotatednessRawResults.setObjectName("rotatednessRawResults")
        self.verticalLayout_5.addWidget(self.rotatednessRawResults)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.rotatednessScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.rotateLayout.addWidget(self.rotatednessScrollArea)
        self.rotateGraphLayout = QtWidgets.QVBoxLayout()
        self.rotateGraphLayout.setObjectName("rotateGraphLayout")
        self.rotateLayout.addLayout(self.rotateGraphLayout)
        self.verticalLayout_7.addLayout(self.rotateLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rawText = QtWidgets.QTextEdit(parent=self.tab_3)
        self.rawText.setObjectName("rawText")
        self.verticalLayout_8.addWidget(self.rawText)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.otdButtonsLayout = QtWidgets.QHBoxLayout()
        self.otdButtonsLayout.setObjectName("otdButtonsLayout")
        self.applyWidthCheckbox = QtWidgets.QCheckBox(parent=ResultWindow)
        self.applyWidthCheckbox.setChecked(True)
        self.applyWidthCheckbox.setObjectName("applyWidthCheckbox")
        self.otdButtonsLayout.addWidget(self.applyWidthCheckbox)
        self.applyHeightCheckbox = QtWidgets.QCheckBox(parent=ResultWindow)
        self.applyHeightCheckbox.setChecked(True)
        self.applyHeightCheckbox.setObjectName("applyHeightCheckbox")
        self.otdButtonsLayout.addWidget(self.applyHeightCheckbox)
        self.applyXCheckbox = QtWidgets.QCheckBox(parent=ResultWindow)
        self.applyXCheckbox.setChecked(True)
        self.applyXCheckbox.setObjectName("applyXCheckbox")
        self.otdButtonsLayout.addWidget(self.applyXCheckbox)
        self.applyYCheckbox = QtWidgets.QCheckBox(parent=ResultWindow)
        self.applyYCheckbox.setChecked(True)
        self.applyYCheckbox.setObjectName("applyYCheckbox")
        self.otdButtonsLayout.addWidget(self.applyYCheckbox)
        self.applyRotationCheckbox = QtWidgets.QCheckBox(parent=ResultWindow)
        self.applyRotationCheckbox.setChecked(True)
        self.applyRotationCheckbox.setObjectName("applyRotationCheckbox")
        self.otdButtonsLayout.addWidget(self.applyRotationCheckbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.otdButtonsLayout.addItem(spacerItem)
        self.importOtdButton = QtWidgets.QPushButton(parent=ResultWindow)
        self.importOtdButton.setObjectName("importOtdButton")
        self.importOtdButton.clicked.connect(ResultWindow.import_otd_config)
        self.otdButtonsLayout.addWidget(self.importOtdButton)
        self.applyOtdButton = QtWidgets.QPushButton(parent=ResultWindow)
        self.applyOtdButton.setObjectName("applyOtdButton")
        self.applyOtdButton.clicked.connect(ResultWindow.apply_otd_adjustments)
        self.otdButtonsLayout.addWidget(self.applyOtdButton)
        self.verticalLayout_3.addLayout(self.otdButtonsLayout)

        self.otd_config_path = None
        self.otd_config = None
        self.otd_tablet = None
        self.skew_x_px = None
        self.skew_y_px = None
        self.horizontal_aim_pct = None
        self.vertical_aim_pct = None
        self.rotation_deg = None

        self.retranslateUi(ResultWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ResultWindow)

    def retranslateUi(self, ResultWindow):
        _translate = QtCore.QCoreApplication.translate
        ResultWindow.setWindowTitle(_translate("ResultWindow", "Dialog"))
        self.label_2.setText(_translate("ResultWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">Green</span> means <span style=\" color:#00aa00;\">significancy</span>; recommend to <span style=\" color:#00aa00;\">follow</span> the result</p></body></html>"))
        self.label.setText(_translate("ResultWindow", "<html><head/><body><p><span style=\" color:#aa0000;\">Red</span> means <span style=\" color:#aa0000;\">insignificancy</span>; recommend to <span style=\" color:#aa0000;\">disregard</span> the result</p></body></html>"))
        self.skewednessTitle.setText(_translate("ResultWindow", "<b>Skewedness</b>"))
        self.skewednessUpward.setText(_translate("ResultWindow", "TextLabel"))
        self.skewednessRightward.setText(_translate("ResultWindow", "TextLabel"))
        self.widenessTitle.setText(_translate("ResultWindow", "<b>Wideness</b>"))
        self.widenessHorizontal.setText(_translate("ResultWindow", "TextLabel"))
        self.widenessVertical.setText(_translate("ResultWindow", "TextLabel"))
        self.widenessRawResultsTitle.setText(_translate("ResultWindow", "<b>Raw Results</b>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ResultWindow", "Wideness"))
        self.label_3.setText(_translate("ResultWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">Green</span> means <span style=\" color:#00aa00;\">significancy</span>; recommend to <span style=\" color:#00aa00;\">follow</span> the result</p></body></html>"))
        self.label_4.setText(_translate("ResultWindow", "<html><head/><body><p><span style=\" color:#aa0000;\">Red</span> means <span style=\" color:#aa0000;\">insignificancy</span>; recommend to <span style=\" color:#aa0000;\">disregard</span> the result</p></body></html>"))
        self.rotatednessTitle.setText(_translate("ResultWindow", "<b>Rotatedness</b>"))
        self.rotatednessResult.setText(_translate("ResultWindow", "TextLabel"))
        self.rotatednessRawResultsTitle.setText(_translate("ResultWindow", "<b>Raw Results</b>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ResultWindow", "Rotatedness"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ResultWindow", "Raw"))
        self.applyWidthCheckbox.setText(_translate("ResultWindow", "Apply Width"))
        self.applyHeightCheckbox.setText(_translate("ResultWindow", "Apply Height"))
        self.applyXCheckbox.setText(_translate("ResultWindow", "Apply X"))
        self.applyYCheckbox.setText(_translate("ResultWindow", "Apply Y"))
        self.applyRotationCheckbox.setText(_translate("ResultWindow", "Apply Rotation"))
        self.importOtdButton.setText(_translate("ResultWindow", "Import OTD config"))
        self.applyOtdButton.setText(_translate("ResultWindow", "Apply OTD adjustments"))

    def set_otd_checkbox_defaults(self):
        """Toggle OTD parameter checkboxes based on metric significance."""

        def _is_significant(label: QtWidgets.QLabel) -> bool:
            style = (label.styleSheet() or "").lower()
            return "lightgreen" in style or "#00aa00" in style

        self.applyWidthCheckbox.setChecked(_is_significant(self.widenessHorizontal))
        self.applyHeightCheckbox.setChecked(_is_significant(self.widenessVertical))
        self.applyXCheckbox.setChecked(_is_significant(self.skewednessRightward))
        self.applyYCheckbox.setChecked(_is_significant(self.skewednessUpward))
        self.applyRotationCheckbox.setChecked(_is_significant(self.rotatednessResult))


def _format_three_decimals(value):
    return f"{round(float(value), 3):.3f}"


def import_otd_config(self):
    file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
        self,
        "Select OTD settings.json",
        "",
        "JSON Files (*.json);;All Files (*)",
    )

    if not file_path:
        return

    try:
        with open(file_path, "r", encoding="utf-8") as file:
            data = json.load(file)
    except Exception as error:  # pylint: disable=broad-except
        QtWidgets.QMessageBox.critical(
            self,
            "Failed to import",
            f"Could not read the selected file.\n\n{error}",
        )
        return

    tablet_data = None
    if isinstance(data, dict):
        potential_tablets = []

        if "Tablet" in data:
            potential_tablets.append(data.get("Tablet"))

        profiles = data.get("Profiles")
        if isinstance(profiles, list):
            for profile in profiles:
                if not isinstance(profile, dict):
                    continue

                if "Tablet" in profile:
                    potential_tablets.append(profile.get("Tablet"))

                absolute_mode_settings = profile.get("AbsoluteModeSettings")
                if isinstance(absolute_mode_settings, dict) and "Tablet" in absolute_mode_settings:
                    potential_tablets.append(absolute_mode_settings.get("Tablet"))

        for candidate in potential_tablets:
            if isinstance(candidate, dict):
                tablet_data = candidate
                break

    if not isinstance(tablet_data, dict):
        QtWidgets.QMessageBox.warning(
            self,
            "Tablet config not found",
            "Could not locate a Tablet section in the selected configuration.",
        )
        return

    self.otd_config_path = file_path
    self.otd_config = data
    self.otd_tablet = tablet_data

    self.tablet_width = tablet_data.get("Width")
    self.tablet_height = tablet_data.get("Height")
    self.tablet_x = tablet_data.get("X")
    self.tablet_y = tablet_data.get("Y")
    self.tablet_rotation = tablet_data.get("Rotation")

    summary = (
        f"Width: {_format_three_decimals(self.tablet_width)}\n"
        f"Height: {_format_three_decimals(self.tablet_height)}\n"
        f"X: {_format_three_decimals(self.tablet_x)}\n"
        f"Y: {_format_three_decimals(self.tablet_y)}\n"
        f"Rotation: {_format_three_decimals(self.tablet_rotation)}"
    )

    QtWidgets.QMessageBox.information(
        self,
        "OTD Tablet Config Imported",
        summary,
    )


Ui_ResultWindow.import_otd_config = import_otd_config


def apply_otd_adjustments(self):
    if not getattr(self, "otd_tablet", None):
        QtWidgets.QMessageBox.warning(
            self,
            "No config imported",
            "No OpenTabletDriver config imported. Please import a config first.",
        )
        return

    required_metrics = {
        "skew_x_px": getattr(self, "skew_x_px", None),
        "skew_y_px": getattr(self, "skew_y_px", None),
        "horizontal_aim_pct": getattr(self, "horizontal_aim_pct", None),
        "vertical_aim_pct": getattr(self, "vertical_aim_pct", None),
        "rotation_deg": getattr(self, "rotation_deg", None),
    }

    if any(value is None for value in required_metrics.values()):
        QtWidgets.QMessageBox.warning(
            self,
            "Results unavailable",
            "Analyzer results are missing; cannot apply adjustments.",
        )
        return

    try:
        w = float(self.otd_tablet.get("Width", 0))
        h = float(self.otd_tablet.get("Height", 0))
        x = float(self.otd_tablet.get("X", 0))
        y = float(self.otd_tablet.get("Y", 0))
        rot = float(self.otd_tablet.get("Rotation", 0.0))
    except (TypeError, ValueError):
        QtWidgets.QMessageBox.critical(
            self,
            "Invalid tablet values",
            "Current Tablet values are invalid or missing.",
        )
        return

    horiz_pct = float(required_metrics["horizontal_aim_pct"])
    vert_pct = float(required_metrics["vertical_aim_pct"])
    skew_x_px = float(required_metrics["skew_x_px"])
    skew_y_px = float(required_metrics["skew_y_px"])
    rotation_delta = float(required_metrics["rotation_deg"])

    new_w = w * (horiz_pct / 100.0)
    new_h = h * (vert_pct / 100.0)

    new_x = x + skew_x_px
    new_y = y - skew_y_px

    new_rot = rot + rotation_delta

    apply_width = getattr(self, "applyWidthCheckbox", None)
    apply_height = getattr(self, "applyHeightCheckbox", None)
    apply_x = getattr(self, "applyXCheckbox", None)
    apply_y = getattr(self, "applyYCheckbox", None)
    apply_rotation = getattr(self, "applyRotationCheckbox", None)

    updated_tablet = dict(self.otd_tablet)

    if apply_width is None or apply_width.isChecked():
        updated_tablet["Width"] = round(new_w, 3)

    if apply_height is None or apply_height.isChecked():
        updated_tablet["Height"] = round(new_h, 3)

    if apply_x is None or apply_x.isChecked():
        updated_tablet["X"] = round(new_x, 3)

    if apply_y is None or apply_y.isChecked():
        updated_tablet["Y"] = round(new_y, 3)

    if apply_rotation is None or apply_rotation.isChecked():
        updated_tablet["Rotation"] = round(new_rot, 3)

    default_dir = Path(self.otd_config_path).parent if self.otd_config_path else Path.cwd()
    original_name = Path(self.otd_config_path).stem if self.otd_config_path else "settings"
    suggested = default_dir / f"{original_name}_aim_adjusted.json"

    save_path, _ = QtWidgets.QFileDialog.getSaveFileName(
        self,
        "Save adjusted OpenTabletDriver config",
        str(suggested),
        "JSON files (*.json);;All files (*)",
    )

    if not save_path:
        return

    self.otd_tablet.update(updated_tablet)

    try:
        with open(save_path, "w", encoding="utf-8") as file:
            json.dump(self.otd_config, file, indent=2)
    except Exception as error:  # pylint: disable=broad-except
        QtWidgets.QMessageBox.critical(
            self,
            "Failed to save",
            f"Could not save the adjusted config.\n\n{error}",
        )
        return

    QtWidgets.QMessageBox.information(
        self,
        "Config saved",
        f"New OpenTabletDriver config saved to:\n{save_path}",
    )


Ui_ResultWindow.apply_otd_adjustments = apply_otd_adjustments
